In [40]:
import keras
import os
import pandas as pd
import numpy as np
import matplotlib as plt
from keras.datasets import mnist
import pprint
cwd = os.getcwd()

path = cwd+'/sign_language/sign_mnist_train.csv'

y_train = np.genfromtxt(path, skip_header=1, delimiter=',', usecols=[0]])
x_train = np.genfromtxt(path, skip_header=1, delimiter=',', usecols=[x for x in range(1,785)])

print(x_train.shape)

# (x_train, y_train), (x_test, y_test) = mnist.load_data()
# print(x_train.shape)

# print(train.shape)

(27455, 784)


In [43]:
x_train = x_train.reshape(27455, 28,28)

print(x_train)

[[[107. 118. 127. ... 170. 170. 169.]
  [111. 121. 129. ... 171. 171. 170.]
  [113. 123. 131. ... 171. 171. 171.]
  ...
  [142. 150. 159. ... 202. 201. 200.]
  [142. 151. 160. ... 204. 203. 202.]
  [142. 151. 160. ... 204. 203. 202.]]

 [[155. 157. 156. ... 138.  92. 108.]
  [158. 159. 159. ... 142. 116. 143.]
  [161. 161. 161. ... 147. 125. 140.]
  ...
  [162. 159. 145. ...  91. 101.  94.]
  [153. 139. 115. ...  97.  95. 120.]
  [135. 116.  95. ... 103. 135. 149.]]

 [[187. 188. 188. ...  66.  77.  83.]
  [188. 189. 189. ...  73.  73.  71.]
  [190. 190. 190. ...  74.  68.  61.]
  ...
  [212. 198. 175. ... 195. 193. 192.]
  [202. 179. 152. ... 195. 194. 193.]
  [198. 166. 132. ... 195. 194. 195.]]

 ...

 [[174. 174. 174. ... 160. 158. 156.]
  [178. 178. 177. ... 162. 160. 158.]
  [181. 180. 180. ... 164. 162. 161.]
  ...
  [215. 216. 216. ... 201. 199. 198.]
  [216. 217. 217. ... 201. 200. 198.]
  [217. 217. 217. ... 202. 200. 200.]]

 [[177. 181. 184. ... 181. 179. 177.]
  [179. 182.